In [43]:
a = np.arange(1,10,4)
print(a)
print(type(a))

[1 5 9]
<class 'numpy.ndarray'>


In [47]:
a = np.arange(10)
print(a)
type(a)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [48]:
#default counting starting from 0 so naturally ending at second last no
a1 = range(1,5)
print(list(a1))
print(type(a1))

[1, 2, 3, 4]
<class 'range'>


In [49]:
a3 = np.arange(0.5 , 13.2 , 0.7)
print(a3)

[ 0.5  1.2  1.9  2.6  3.3  4.   4.7  5.4  6.1  6.8  7.5  8.2  8.9  9.6
 10.3 11.  11.7 12.4 13.1]


In [50]:
int_array = np.array([1.2 , 3 , 4 , 5 , 6])
print(int_array.dtype)
print(int_array.ndim)

float64
1


In [55]:
print(int_array[:-1])

[1.2 3.  4.  5. ]


In [56]:
print(int_array[::-1]) #prints in reverse order

[6.  5.  4.  3.  1.2]


In [58]:
print(int_array[::-2]) #prints in reverse order with sterp of two

[6.  4.  1.2]


In [60]:
print(int_array[::-3]) #prints in reverse order with sterp of two

[6. 3.]


In [61]:
array_of_float = np.array([1.2 , 3.4 , 4.5 , 5.6 , 6.7 , 7.8 , 8.9],float)
print(array_of_float.mean())

5.442857142857143


In [62]:
print(array_of_float.max())

8.9


In [63]:
#index of max value
print(array_of_float.argmax())

6


In [64]:
print(array_of_float > 5)

[False False False  True  True  True  True]


In [65]:
print(np.median(array_of_float))

5.6


In [66]:
greater_than = a > 5.5
print(any(greater_than))
print(all(greater_than))

True
False


In [67]:
first_array = [1,2,3]
second_array = [4,5,6]
print(np.concatenate((first_array,second_array)))

[1 2 3 4 5 6]


In [1]:
import numpy
arr = numpy.array([1 ,2 ,3 ,4 ,5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np
arr = np.array([1 ,2 ,3 ,4 ,5 ,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
print(np.__version__)

1.18.1


In [4]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [5]:
import numpy as np
arr = np.array([[1 ,2 ,3 ,4 ,5 ,6] ,[7 ,8 ,9 ,10]])
print(arr)

[list([1, 2, 3, 4, 5, 6]) list([7, 8, 9, 10])]


In [6]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np
arr = np.array([[[1 ,2 ,3] ,[4 ,5 ,6]] ,[[1 ,2 ,3] , [4 ,5 ,6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [9]:
import numpy as np
a = np.array(42)
b = np.array([1 ,2 ,3 ,4 ,5])
c = np.array([[1 ,2 ,3 ] , [4 ,5 ,6 ]])
d = np.array([[[1 ,2 ,3 ] , [4 ,5 ,6 ]] , [[1 ,2 ,3 ] , [4 ,5 ,6 ]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [10]:
import numpy as np
arr = np.array([1 ,2 ,3 ,4 ,5] , ndmin = 5)
print(arr)
print('number of dimension:' ,arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimension: 5


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [15]:
first_matrix = np.arange(30).reshape(5,6)

In [13]:
first_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [17]:
first_matrix.shape

(5, 6)

In [18]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.ones((4,4) ,dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
#find the max
print(first_matrix)
print("The max is : {0}".format(first_matrix.max()))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
The max is : 29


In [28]:
print(first_matrix)
print("The max is : {0}".format(first_matrix.max(axis=0)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
The max is : [24 25 26 27 28 29]


In [29]:
print(first_matrix)
print("The max is :{0}".format(first_matrix.sum(axis=1)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
The max is :[ 15  51  87 123 159]


In [30]:
#nparrays vs lists
#adding-list
first_list = [1 ,2 ,3]
second_list = [4 ,5 ,6]
print(first_list + second_list) #concatenates

[1, 2, 3, 4, 5, 6]


In [32]:
print(np.array(first_list) + np.array(second_list))

[5 7 9]


In [33]:
speed = [1 , 2 , 3 , 4 , 5 , 6]
sai = numpy.std(speed)
print(sai)

1.707825127659933


In [34]:
speed = [1 , 2 , 3 , 4 , 5 , 6]
sai = numpy.var(speed)
print(sai)

2.9166666666666665


In [35]:
age =  [1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10]
sai = numpy.percentile(age , 75)
print(sai)

7.75


In [36]:
sai = numpy.random.uniform(0.0 , 5.0 , 250)
print(sai)

[2.00309247e-02 2.01188270e+00 3.87872619e+00 4.48061284e+00
 2.75053524e+00 1.28525831e+00 4.62089896e-01 4.95030538e+00
 2.52137439e+00 4.54328265e+00 1.73535703e+00 4.00812207e-01
 1.56567782e+00 1.83607922e-01 2.71774409e+00 8.53856686e-01
 1.91513321e+00 2.02252245e+00 2.01325498e+00 3.11728975e+00
 1.07489084e+00 1.82452867e+00 2.57516486e+00 1.84836248e+00
 4.32944738e+00 3.56392092e+00 3.02640682e+00 3.68898142e+00
 4.54571984e+00 4.76235095e+00 3.52432752e-03 6.20026621e-01
 3.29956709e+00 5.51331369e-01 4.51014742e-01 3.30921662e+00
 1.18007598e+00 5.82810227e-01 1.89199216e+00 2.87808351e+00
 2.13954887e+00 3.70788350e+00 4.30905891e-01 1.82392667e+00
 2.02259974e+00 3.45407389e+00 1.16829024e+00 9.56439225e-01
 7.97863266e-01 1.23912579e-02 2.11919984e+00 1.51995373e+00
 1.37412367e+00 4.68180993e+00 1.99205846e+00 3.93046654e+00
 2.01535721e+00 4.64033752e+00 2.36315839e+00 4.42077783e+00
 1.29815051e+00 2.67087317e+00 3.15412512e+00 2.05530894e-02
 3.38552617e+00 1.979277

In [41]:
x = numpy.random.normal(5 , 1 , 100000)

In [42]:
x

array([6.53264797, 3.64172456, 6.95491776, ..., 4.38899024, 5.27182944,
       5.72562222])

In [1]:
s = np.arange(9).reshape(3,3)

<IPython.core.display.Javascript object>

In [2]:
s

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
s < 3

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [4]:
np.less(s , 3)

<IPython.core.display.Javascript object>

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [5]:
np.sum(s < 6 , axis=0) #axis=1 row , axis=0 column

<IPython.core.display.Javascript object>

array([2, 2, 2])

In [6]:
np.any(s < 6)

<IPython.core.display.Javascript object>

True

In [7]:
np.any(s > 9)

<IPython.core.display.Javascript object>

False

In [8]:
np.any(s > 7) #checks any value

<IPython.core.display.Javascript object>

True

In [9]:
np.all(s < 0)

<IPython.core.display.Javascript object>

False

In [10]:
np.all(s < 2)

<IPython.core.display.Javascript object>

False

In [11]:
np.all(s < 9) #checks all value

<IPython.core.display.Javascript object>

True

In [12]:
rand = np.random.RandomState(42)
x = rand.randint(100 , size = 10)
x

<IPython.core.display.Javascript object>

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [13]:
a = np.random.randint(100 , size=10)

<IPython.core.display.Javascript object>

In [14]:
a

array([75, 44, 16,  3, 48, 80, 39, 85, 48, 39])

In [15]:
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [16]:
a =[3,5,7,0,2]

In [17]:
x[a]

array([71, 20, 86, 51, 14])